# Sourcing Files
source = ~/.config/hypr/mocha.conf # Mocha Theme
source = ~/.config/hypr/modules/monitors.conf # Monitors
source = ~/.config/hypr/modules/programs.conf # My Programs
source = ~/.config/hypr/modules/autostart.conf # Autostart
source = ~/.config/hypr/modules/enviroment.conf # Autostart
source = ~/.config/hypr/modules/decoration.conf # Decorations
source = ~/.config/hypr/modules/windowrules.conf # Window Rules
source = ~/.config/hypr/modules/input.conf # Input
source = ~/.config/hypr/modules/binds.conf # Binds
source = ~/.config/hypr/modules/animations.conf # Animations
source = ~/.config/hypr/modules/layout.conf # Layout
source = ~/.config/hypr/modules/misc.conf # Miscs
